### ISSUE TITLE
Copilot-like features

### ISSUE THREAD

**Issue by AnselmC** [stuhlmueller/gpt.el#20]
I think it'd be great if we'd have copilot-like features in emacs. 
Is this something you'd like to be part of `gpt.el` or do you want to keep its scope limited to a chat-interface?

I briefly hacked the following together and would either create a PR here or create a separate package for this:

![copilot](https://github.com/user-attachments/assets/c25582fb-d7a4-4024-86be-bad1ffa406b8)

**Comment by stuhlmueller** [comment]
Depends on how simple and general the implementation is - hoping to keep this package pretty small. There are already lots of other complex emacs packages around gpt usage. Not tied to the chat interface though.

**Comment by AnselmC** [comment]
Ok. Created a draft here: https://github.com/stuhlmueller/gpt.el/pull/21
Let me know if this would fit or not

**Comment by stuhlmueller** [comment]
Thank you - haven't had time to review yet, but in the meantime another related feature that came to mind that could be useful is inline transformations. You select a region, press a button, enter an instruction, and it inserts the LLM-transformed region into the current buffer as a preview, asking you to accept/reject.

**Comment by AnselmC** [comment]
something like this?

https://github.com/user-attachments/assets/2529a525-1813-4ced-a78f-15f5c98bdb5e
