### ISSUE TITLE
GPT-3.5?

### ISSUE THREAD

**Issue by benthamite** [stuhlmueller/gpt.el#5]
Is there a way to make the package use GPT-3.5? Setting `gpt-openai-engine` to `"gpt-3.5-turbo"` (which appears to be the name of GPT-3.5 according to [this page](https://platform.openai.com/docs/models/overview)) does not work unfortunately.

**Comment by benthamite** [comment]
FYI, [this package](https://github.com/emacs-openai/openai) was just released, which uses an Elisp library for the OpenAI API, so it may not be worth putting in the effort to update this one.

**Comment by stuhlmueller** [comment]
If we want to continue working on it (maybe as a simpler alternative to the chatgpt package @benthamite  mentioned), we could use the [openai](https://github.com/emacs-openai/openai) package that the chatgpt package depends on.

**Comment by stuhlmueller** [comment]
Implemented in [a38c152](https://github.com/stuhlmueller/gpt.el/commit/a38c152caa99ca30af86040907f70b027173c19d)
