### ISSUE TITLE
Python syntax error (OSX Ventura - M1 Mac)

### ISSUE THREAD

**Issue by rmulligan** [stuhlmueller/gpt.el#8]
I'm receiving the following error when calling gpt-dwim:

  File "/Users/ryanmulligan/Zettels/configuration/.emacs.d/.local/straight/build-28.2/gpt/gpt.py", line 27
    def parse_args() -> argparse.Namespace:
                     ^
SyntaxError: invalid syntax

Which version of python is required for this package? I am using 3.11.3.

**Comment by stuhlmueller** [comment]
That should be fine. Is that the version you get when you run `run-python` in Emacs?
